# Generated by Django 3.0.3 on 2020-03-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='renter',
        ),
        migrations.AddField(
            model_name='picture',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='managecar.Car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
