# Generated by Django 3.0.3 on 2020-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0003_rent_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BLUE', 'น้ำเงิน'), ('RED', 'แดง'), ('PINK', 'ชมพู'), ('ORANGE', 'ส้ม'), ('BLACK', 'ดำ'), ('WHITE', 'ขาว'), ('SILVER', 'เงิน'), ('BRONZ', 'บรอนซ์'), ('YELLOW', 'เหลือง')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NO AVAILABLE', 'Not Available'), ('HIDE', 'Hide')], max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_gear',
            field=models.CharField(choices=[('AUTO', 'เกียร์ธรรมดา'), ('MANUAL', 'เกียร์อัตโนมัติ'), ('CBT', 'เกียร์ CVT'), ('DTC', 'เกียร์กึ่งอัตโนมัติ และ เกียร์คลัตช์คู่ DCT')], max_length=10),
        ),
    ]
