# Generated by Django 3.0.3 on 2020-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0005_auto_20200308_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('promotion_code', models.CharField(max_length=8, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_cost', models.FloatField()),
                ('expire_day', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
