# Generated by Django 3.0.3 on 2020-03-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0006_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='managecar.Promo'),
            preserve_default=False,
        ),
    ]
