# Generated by Django 3.0.3 on 2020-03-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managecar', '0007_rent_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='car',
        ),
        migrations.AddField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='managecar.Car'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rent',
            name='renter',
        ),
        migrations.AddField(
            model_name='rent',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
