# Generated by Django 3.0.3 on 2020-03-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0008_auto_20200309_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
