# Generated by Django 3.0.3 on 2020-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0010_auto_20200310_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('P', 'Picked'), ('A', 'Approved'), ('D', 'Denied'), ('R', 'Returned'), ('Pe', 'Pending')], max_length=2),
        ),
    ]
