# Generated by Django 3.0.3 on 2020-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0011_auto_20200310_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Picked', 'รับรถเเล้ว'), ('Approved', 'ยืนยัน'), ('Denied', 'ปฎิเสษ'), ('Returned', 'คืนเเล้ว'), ('Pending', 'รอการยืนยัน')], max_length=8),
        ),
    ]
