# Generated by Django 3.0.3 on 2020-03-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0012_auto_20200310_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managecar.Promo'),
        ),
    ]
