# Generated by Django 3.0.3 on 2020-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0013_auto_20200310_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'ว่าง'), ('NO_AVAILABLE', 'ไม่ว่าง'), ('HIDE', 'ซ่อน')], max_length=12),
        ),
    ]
