# Generated by Django 3.0.3 on 2020-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0014_auto_20200310_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('SUV', 'Sport Utility Vehicle'), ('PPV', 'Pick-Up Passenger Vehicle'), ('MPV', 'Multi Purpose Vehicle'), ('ECO', 'Eco Car'), ('HEV', 'Hybrid Electric Vehicles'), ('EV', 'Electric Vehicles'), ('PU', 'Pick-Up Truck'), ('VAN', 'Van Car'), ('SED', 'Sedan'), ('SUP', 'Supercar'), ('COP', 'Coupe')], max_length=3),
        ),
    ]
