# Generated by Django 3.0.3 on 2020-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0015_auto_20200310_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BLUE', 'น้ำเงิน'), ('RED', 'แดง'), ('PINK', 'ชมพู'), ('ORANGE', 'ส้ม'), ('BLACK', 'ดำ'), ('WHI', 'ขาว'), ('SILVER', 'เงิน'), ('BRONZ', 'บรอนซ์'), ('YELLOW', 'เหลือง'), ('Green', 'เขียว')], max_length=10),
        ),
    ]
